### ISSUE TITLE
More default settings for new servers

### ISSUE THREAD

**Issue by God-damnit-all** [RazerMoon/muteNewGuild#1]
This is a very useful plugin, but I wish it would go one step further, enabling suppression of @everyone, @here, and role mentions, as well as disabling mobile push notifications.

![image](https://user-images.githubusercontent.com/53661808/122638467-d5d58700-d0b9-11eb-9611-4fe535e6e092.png)

Mobile push notifications might have to be disabled before the guild is muted, because muting disables them by default. However, if it's not disabled before the guild is muted, then the next time the guild is unmuted, mobile push notifications will be turned back on as well.

I also wouldn't mind a setting to also disable DMs from server members:

![image](https://user-images.githubusercontent.com/53661808/122638509-0cab9d00-d0ba-11eb-8d7c-344002b63758.png)

**Comment by RazerMoon** [comment]
Update should have what you're looking for, I'll look into the direct messages thing later.

**Comment by God-damnit-all** [comment]
> Update should have what you're looking for, I'll look into the direct messages thing later.

Thanks.
